import hashlib
import json
import os
import sys
import time


# ----------------------------------------------------------------
# Files to verify — critical files only
# Generated by tools/generate_checksums.py
# ----------------------------------------------------------------

CHECKSUMS_FILE = os.path.join(os.path.dirname(__file__), "..", "checksums.json")

CRITICAL_FILES = [
    "main.py",
    "core/lifecycle.py",
    "core/threat_model.py",
    "core/entropy_context.py",
    "core/entropy_policy.py",
    "core/policy_enforcer.py",
    "core/exceptions.py",
    "entropy/mixer.py",
    "entropy/commitment_lock.py",
    "entropy/dice.py",
    "entropy/system.py",
    "entropy/external_file.py",
    "seed/bip39.py",
    "seed/verify.py",
    "seed/display.py",
    "seed/wordlist_english.txt",
    "security/adaptive_controller.py",
    "security/integrity_guard.py",
    "security/seed_vault.py",
    "security/passphrase.py",
    "security/tier_policy.py",
    "security/wipe.py",
    "interaction/confirmation_guard.py",
    "interaction/progressive_reveal.py",
    "recovery/slip39.py",
    "recovery/reconstruct.py",
    "cli/interface.py",
    "utils/display.py",
    "utils/qr.py",
]


# ----------------------------------------------------------------
# ANSI colours — inline to avoid circular import with utils/display
# ----------------------------------------------------------------

_GREEN  = "\033[92m"
_RED    = "\033[91m"
_WHITE  = "\033[97m"
_GREY   = "\033[90m"
_ORANGE = "\033[38;5;208m"
_BOLD   = "\033[1m"
_RESET  = "\033[0m"


# ----------------------------------------------------------------
# Core Utilities
# ----------------------------------------------------------------

def _sha256_file(filepath: str) -> str:
    """Compute SHA256 hash of a file. Returns hex string."""
    hasher = hashlib.sha256()

    with open(filepath, "rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            hasher.update(chunk)

    return hasher.hexdigest()


def _get_project_root() -> str:
    """Returns the project root directory."""
    return os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def _resolve_path(relative_path: str) -> str:
    """Resolve a relative file path from the project root."""
    return os.path.join(_get_project_root(), relative_path)


# ----------------------------------------------------------------
# Animated Verification Display
# ----------------------------------------------------------------

def _print_file_result(filename: str, status: str, detail: str = ""):
    """
    Prints a single file verification result line.

    status: "ok" | "fail" | "missing"
    """
    label = f"  {filename}"

    if status == "ok":
        result = f"{_GREEN}[✓] VERIFIED{_RESET}"
    elif status == "fail":
        result = f"{_RED}[✗] TAMPERED{_RESET}"
    elif status == "missing":
        result = f"{_ORANGE}[!] MISSING{_RESET}"
    else:
        result = f"{_GREY}[?] UNKNOWN{_RESET}"

    print(f"{_WHITE}{label:<52}{_RESET} {result}")

    if detail:
        print(f"      {_GREY}{detail}{_RESET}")


def _animate_checking(filename: str):
    """Prints an animated progress bar fill for a file being checked."""
    label = f"  {filename}"
    bar_width = 20

    sys.stdout.write(f"{_WHITE}{label:<52}{_RESET} [")
    sys.stdout.flush()

    for i in range(bar_width):
        time.sleep(0.02)
        if i < bar_width - 1:
            filled = "#" * i + ">" + " " * (bar_width - i - 1)
        else:
            filled = "#" * bar_width
        sys.stdout.write(f"\r{_WHITE}{label:<52}{_RESET} [{_GREEN}{filled}{_RESET}]")
        sys.stdout.flush()

    sys.stdout.write(f"\r{_WHITE}{label:<52}{_RESET} ")
    sys.stdout.flush()


# ----------------------------------------------------------------
# Main Integrity Check
# ----------------------------------------------------------------

def run_integrity_check():
    """
    Verifies SHA256 hashes of all critical files against checksums.json.

    Called from main.py before start_cli().
    Aborts program if any file fails verification.
    """

    print(f"\n{_GREEN}{_BOLD}  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━{_RESET}")
    print(f"{_GREEN}{_BOLD}    PRE-EXECUTION INTEGRITY VERIFICATION{_RESET}")
    print(f"{_GREEN}{_BOLD}  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━{_RESET}\n")

    # ---- Load checksums manifest ----
    checksums_path = os.path.join(_get_project_root(), "checksums.json")

    if not os.path.exists(checksums_path):
        print(f"  {_RED}[✗] checksums.json not found.{_RESET}")
        print(f"  {_GREY}Run tools/generate_checksums.py to generate it.{_RESET}\n")
        sys.exit(1)

    with open(checksums_path, "r") as f:
        checksums = json.load(f)

    # ---- Verify each critical file ----
    all_passed = True
    failed_files = []

    for relative_path in CRITICAL_FILES:
        filepath = _resolve_path(relative_path)

        _animate_checking(relative_path)

        if not os.path.exists(filepath):
            _print_file_result(relative_path, "missing")
            all_passed = False
            failed_files.append(relative_path)
            continue

        if relative_path not in checksums:
            _print_file_result(
                relative_path, "fail",
                "No checksum on record — file may have been added after manifest was generated."
            )
            all_passed = False
            failed_files.append(relative_path)
            continue

        actual_hash   = _sha256_file(filepath)
        expected_hash = checksums[relative_path]

        if actual_hash == expected_hash:
            _print_file_result(relative_path, "ok")
        else:
            _print_file_result(
                relative_path, "fail",
                f"Expected: {expected_hash[:16]}...  Got: {actual_hash[:16]}..."
            )
            all_passed = False
            failed_files.append(relative_path)

    # ---- Result summary ----
    print()

    if all_passed:
        print(f"  {_GREEN}{_BOLD}-------------------------------------------{_RESET}")
        print(f"  {_GREEN}{_BOLD}  ALL FILES VERIFIED — System integrity confirmed.{_RESET}")
        print(f"  {_GREEN}{_BOLD}  [✓] SAFE TO PROCEED. {_RESET}")
        print(f"  {_GREEN}{_BOLD}-------------------------------------------{_RESET}\n")
        time.sleep(0.5)

    else:
        print(f"  {_RED}{_BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━{_RESET}")
        print(f"  {_RED}{_BOLD}  [✗] INTEGRITY CHECK FAILED{_RESET}")
        print(f"  {_RED}{_BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━{_RESET}\n")
        print(f"  {_RED}The following files have been modified or corrupted:{_RESET}\n")

        for f in failed_files:
            print(f"    {_RED}• {f}{_RESET}")

        print(f"\n  {_ORANGE}Do NOT proceed. Your system may be compromised.{_RESET}")
        print(f"  {_ORANGE}Verify the integrity of your USB installation.{_RESET}\n")
        sys.exit(1)

# ----------------------------------------------------------------
# Generator Entry Point
# ----------------------------------------------------------------

if __name__ == "__main__":
    root = _get_project_root()
    checksums = {}
    missing = []

    print(f"\n{_GREEN}{_BOLD}  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━{_RESET}")
    print(f"{_GREEN}{_BOLD}    GENERATING CHECKSUMS MANIFEST{_RESET}")
    print(f"{_GREEN}{_BOLD}  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━{_RESET}\n")

    for relative_path in CRITICAL_FILES:
        filepath = _resolve_path(relative_path)
        label = f"  {relative_path}"

        if os.path.exists(filepath):
            checksums[relative_path] = _sha256_file(filepath)
            print(f"{_WHITE}{label:<52}{_RESET} {_GREEN}[✓] hashed{_RESET}")
        else:
            missing.append(relative_path)
            print(f"{_WHITE}{label:<52}{_RESET} {_ORANGE}[!] MISSING — skipped{_RESET}")

    # Write checksums.json to project root
    output_path = os.path.join(root, "checksums.json")
    with open(output_path, "w") as f:
        json.dump(checksums, f, indent=2)

    print(f"\n  {_GREEN}{_BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━{_RESET}")
    print(f"  {_GREEN}{_BOLD}  [✓] checksums.json generated — {len(checksums)} files hashed{_RESET}")

    if missing:
        print(f"\n  {_ORANGE}  [!] {len(missing)} file(s) were missing and skipped:{_RESET}")
        for m in missing:
            print(f"        {_ORANGE}• {m}{_RESET}")

    print(f"  {_GREEN}{_BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━{_RESET}\n")
    print(f"  {_GREY}Output: {output_path}{_RESET}\n")